name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: SetupJDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Install dependencies
        run: |
          git clone --no-tags --depth 1 --branch legacy https://github.com/EaseCation/Network.git target/Network
          cd target/Network
          mvn -B clean install
      - name: Build
        run: mvn -B clean package
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Nukkit
          path: target/nukkit-1.0-SNAPSHOT.jar
