name: Deploy

on:
  push:
    branches:
      - r20_u5
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: SetupJDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Install dependencies
        run: |
          git clone --no-tags --depth 1 --branch legacy https://github.com/EaseCation/Network.git target/Network
          cd target/Network
          mvn -B clean install
      - name: Build
        run: mvn -B clean source:jar javadoc:jar deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
